[workspace.package]
version = "2.8.0"
authors = ["Andrey Fedotov  <fedotoff@ispras.ru>", "Alexey Vishnyakov <pmvishnya@gmail.com>", "Georgy Savidov <avgor46@ispras.ru>", "Ilya Yegorov <Yegorov_Ilya@ispras.ru>"]

[workspace]
members = ["casr", "libcasr"]

[profile.release]
lto = true
opt-level = 3
