name: coverage

on:
  push:
    branches: [ master, coverage_workflow ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
jobs:
  ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: |
        sudo apt update && sudo apt install -y gdb pip curl python3.10-dev llvm \
            openjdk-17-jdk
        pip3 install atheris
        curl https://sh.rustup.rs -o rustup.sh && chmod +x rustup.sh && \
        ./rustup.sh -y && rm rustup.sh
        rustup install nightly
        export PATH=/root/.cargo/bin:$PATH
        cargo install cargo-fuzz
        export CARGO_INCREMENTAL=0
        export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
        export RUSTDOCFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
        cargo +nightly test --release --verbose
    - uses: actions-rs/grcov@v0.1
